DROP TABLE IF EXISTS public.occurencepoint;

CREATE TABLE IF NOT EXISTS public.occurencepoint_yearly
(
    "X" double precision,
    "Y" double precision,
    "OBJECTID" integer,
    "DISCOVER_YEAR" character varying COLLATE pg_catalog."default",
    "FIRE_NUMBER" character varying COLLATE pg_catalog."default",
    "COUNTY" integer,
    "TOTAL_ACRES_BURNED" double precision,
    "TOPO_LANDFORM_ORIGIN" character varying COLLATE pg_catalog."default",
    "PRESCRIBED_FIRE" character varying COLLATE pg_catalog."default",
    "SLOPE" integer,
    "ELEVATION" integer,
    "OTHER_FUEL_MODEL" character varying COLLATE pg_catalog."default",
    "REP_WX_STATION" integer,
    "LAT_DEG" integer,
    "LAT_MIN" integer,
    "LAT_SEC" integer,
    "LONG_DEG" integer,
    "LONG_MIN" integer,
    "LONG_SEC" integer,
    "TOWNSHIP" character varying COLLATE pg_catalog."default",
    "RANGE" character varying COLLATE pg_catalog."default",
    "SECTION" integer,
    "SUB_SECTION" character varying COLLATE pg_catalog."default",
    "WIND_SPEED" integer,
    "DISCOVERED_BY_DESCR" character varying COLLATE pg_catalog."default",
    "FIRE_NAME" character varying COLLATE pg_catalog."default",
    "RECORD_ENTRY_DATE" time with time zone,
    "AGENCY_ACRES" double precision,
    "OTHER_ACRES_INSIDE" double precision,
    "OTHER_ACRES_OUTSIDE" double precision,
    "DISTRICT" integer,
    "LOCAL_FIRE_NUMBER" character varying COLLATE pg_catalog."default",
    "PRESCRIBED_ACRES" double precision,
    "IGNITION" time with time zone,
    "DISCOVERY" time with time zone,
    "STRATEGY_MET" time with time zone,
    "FIRE_OUT" time with time zone,
    "SUBMITTED_DATE" time with time zone,
    "APPROVED_DATE" time with time zone,
    "STATE_CODE" character varying COLLATE pg_catalog."default",
    "CONTAINED" time with time zone,
    "COUNTY_STATE_CODE" character varying COLLATE pg_catalog."default",
    "LOCATION" character varying COLLATE pg_catalog."default",
    "FIRE_MANAGEMENT_CODE" character varying COLLATE pg_catalog."default",
    "COMPLEX_FIRE" character varying COLLATE pg_catalog."default",
    "WUI_FIRE" character varying COLLATE pg_catalog."default",
    "WUI_ACRES" character varying COLLATE pg_catalog."default",
    "OBJECTIVES" character varying COLLATE pg_catalog."default",
    "CREATED_DATE" time with time zone,
    "LAST_MODIFIED_DATE" time with time zone,
    "POO_LATITUDE" double precision,
    "POO_LONGITUDE" double precision,
    "COMPLEX_NAME" character varying COLLATE pg_catalog."default",
    "STATION_TYPE" integer,
    "STATION_NAME" character varying COLLATE pg_catalog."default",
    "ASPECT" character varying COLLATE pg_catalog."default",
    "PRINCIPAL_MERIDIAN" character varying COLLATE pg_catalog."default",
    "STATISTICAL_CAUSE" character varying COLLATE pg_catalog."default",
    "FIRE_SIZE_CLASS" character varying COLLATE pg_catalog."default",
    "FIRE_DETECTOR" character varying COLLATE pg_catalog."default",
    "NFDRS_FUEL_MODEL" character varying COLLATE pg_catalog."default",
    "COVER_CLASS" character varying COLLATE pg_catalog."default",
    "FIRE_INTENSITY_LEVEL" character varying COLLATE pg_catalog."default",
    "INITIAL_STRATEGY" character varying COLLATE pg_catalog."default",
    "LOCAL_TIMEZONE" character varying COLLATE pg_catalog."default",
    "PROTECTING_AGENCY_AT_ORIGIN" character varying COLLATE pg_catalog."default",
    "OWNERSHIP_AGENCY_AT_ORIGIN" character varying COLLATE pg_catalog."default",
    "STATE_NAME" character varying COLLATE pg_catalog."default",
    "COUNTY_NAME" character varying COLLATE pg_catalog."default",
    "REPORT_UNIT" character varying COLLATE pg_catalog."default",
    "REPORT_UNIT_NAME" character varying COLLATE pg_catalog."default",
    "ADMIN_UNIT" character varying COLLATE pg_catalog."default",
    "ADMIN_UNIT_NAME" character varying COLLATE pg_catalog."default",
    "OWNERSHIP_UNIT" character varying COLLATE pg_catalog."default",
    "OWNERSHIP_UNIT_NAME" character varying COLLATE pg_catalog."default",
    "PROTECTION_UNIT" integer,
    "PROTECTION_UNIT_NAME" character varying COLLATE pg_catalog."default",
    "INITIAL_RESPONSE" time with time zone,
    "SHAPE" character varying COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

--ALTER TABLE IF EXISTS public.usfs
--    OWNER to postgres;

COPY occurencepoint_yearly -- table name
FROM '/Users/lucaluna/460/FIRESTAT_Fire_Occurrence_-_Yearly_Update_(Feature_Layer).csv'
DELIMITER ','
CSV HEADER;
